version: '3'
services:
  storage0:
    container_name: storage1
    image: denghc/fastdfs:1.0.0
    command: storage
    network_mode: host
    environment:
      - TRACKER_SERVER=10.1.12.174:22122
      - PORT=23001
      - HTTP_SERVER_PORT=8889
      - GROUP_NAME=group1
    volumes:
      - /data/fdfs/storage1:/var/fdfs
